<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### diohe

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```

```{r}
Dataset <- readXL("C:/Users/diohe/Downloads/Dados_Renda_Trabalho01 (1).xlsx", rownames=FALSE, header=TRUE, na="", 
  sheet="Dados_Trabalho_01", stringsAsFactors=TRUE)
```


```{r}
dados<-Dataset$renda
```


```{r}
dados
```


```{r}
dados <- Dataset$renda
```


```{r}
dados
```


```{r}
n<-150
```


```{r}
dados <- Dataset$renda
```


```{r}
dados
```


```{r}
n<-150
```


```{r}
n
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
for (i in 1:n) {
dados[i]
}
```


```{r}
Dataset <- within(Dataset, {
  Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```

```{r}
dados <- Dataset$renda
```


```{r}
dados
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
dados <- Dataset$renda
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
situacao1<-c()
```


```{r}
situacao2<-c()
```


```{r}
situacao3<-c()
```


```{r}
situacao4<-c()
```


```{r}
situacao5<-c()
```


```{r}
situacao6<-c()
```


```{r}
situacao7<-c()
```


```{r}
c1<-1
```


```{r}
c2<-1
```


```{r}
c3<-1
```


```{r}
c4<-1
```


```{r}
c5<-1
```


```{r}
c6<-1
```


```{r}
c7<-1
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao1[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao1[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao1[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao1[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao1[c6]<-dados[i]
c6<-c6+1
} else {
situacao1[c7]<-dados[i]
c7<-c7+1
}
}
```


```{r}
situacao1
```


```{r}
situacao2
```


```{r}
situacao3
```


```{r}
situacao4
```


```{r}
situacao5
```


```{r}
situacao6
```


```{r}
situacao7
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao2[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao3[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao4[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao5[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao6[c6]<-dados[i]
c6<-c6+1
} else {
situacao7[c7]<-dados[i]
c7<-c7+1
}
}
```


```{r}
situacao1
```


```{r}
situacao2
```


```{r}
situacao3
```


```{r}
situacao4
```


```{r}
situacao5
```


```{r}
situacao6
```


```{r}
situacao7
```


```{r}
Dataset <- readXL("C:/Users/diohe/Downloads/Dados_Renda_Trabalho01 (1).xlsx", rownames=FALSE, header=TRUE, na="",
sheet="Dados_Trabalho_01", stringsAsFactors=TRUE)
```


```{r}
dados <- Dataset$renda
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
situacao1<-c()
```


```{r}
situacao2<-c()
```


```{r}
situacao3<-c()
```


```{r}
situacao4<-c()
```


```{r}
situacao5<-c()
```


```{r}
situacao6<-c()
```


```{r}
situacao7<-c()
```


```{r}
c1<-1
```


```{r}
c2<-1
```


```{r}
c3<-1
```


```{r}
c4<-1
```


```{r}
c5<-1
```


```{r}
c6<-1
```


```{r}
c7<-1
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao2[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao3[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao4[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao5[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao6[c6]<-dados[i]
c6<-c6+1
} else {
situacao7[c7]<-dados[i]
c7<-c7+1
}
}
```


```{r}
situacao1
```


```{r}
situacao2
```


```{r}
situacao3
```


```{r}
situacao4
```


```{r}
situacao5
```


```{r}
situacao6
```


```{r}
situacao7
```


```{r}
Dataset <- readXL("C:/Users/diohe/Downloads/Dados_Renda_Trabalho01 (1).xlsx", rownames=FALSE, header=TRUE, na="",
sheet="Dados_Trabalho_01", stringsAsFactors=TRUE)
```


```{r}
dados <- Dataset$renda
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
situacao1<-c()
```


```{r}
situacao2<-c()
```


```{r}
situacao3<-c()
```


```{r}
situacao4<-c()
```


```{r}
situacao5<-c()
```


```{r}
situacao6<-c()
```


```{r}
situacao7<-c()
```


```{r}
c1<-1
```


```{r}
c2<-1
```


```{r}
c3<-1
```


```{r}
c4<-1
```


```{r}
c5<-1
```


```{r}
c6<-1
```


```{r}
c7<-1
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao2[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao3[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao4[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao5[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao6[c6]<-dados[i]
c6<-c6+1
} else {
situacao7[c7]<-dados[i]
c7<-c7+1
}
}
```


```{r}
situacao1
```


```{r}
situacao2
```


```{r}
situacao3
```


```{r}
situacao4
```


```{r}
situacao5
```


```{r}
situacao6
```


```{r}
situacao7
```


```{r}
amostra1<-sample(situacao1,TamanhoAmos[1])
```


```{r}
amostra2<-sample(situacao2,TamanhoAmos[2])
```


```{r}
amostra3<-sample(situacao3,TamanhoAmos[3])
```


```{r}
amostra4<-sample(situacao4,TamanhoAmos[4])
```


```{r}
amostra5<-sample(situacao5,TamanhoAmos[5])
```


```{r}
amostra6<-sample(situacao6,TamanhoAmos[6])
```


```{r}
amostra7<-sample(situacao7,TamanhoAmos[7])
```


```{r}
amostra1
```


```{r}
amostra2
```


```{r}
amostra3
```


```{r}
amostra4
```


```{r}
amostra5
```


```{r}
amostra6
```


```{r}
amostra7
```


```{r}
Dataset <- readXL("C:/Users/diohe/Downloads/Dados_Renda_Trabalho01 (1).xlsx", rownames=FALSE, header=TRUE, na="",
sheet="Dados_Trabalho_01", stringsAsFactors=TRUE)
```


```{r}
dados <- Dataset$renda
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
situacao1<-c()
```


```{r}
situacao2<-c()
```


```{r}
situacao3<-c()
```


```{r}
situacao4<-c()
```


```{r}
situacao5<-c()
```


```{r}
situacao6<-c()
```


```{r}
situacao7<-c()
```


```{r}
c1<-1
```


```{r}
c2<-1
```


```{r}
c3<-1
```


```{r}
c4<-1
```


```{r}
c5<-1
```


```{r}
c6<-1
```


```{r}
c7<-1
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao2[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao3[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao4[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao5[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao6[c6]<-dados[i]
c6<-c6+1
} else {
situacao7[c7]<-dados[i]
c7<-c7+1
}
}
```


```{r}
situacao1
```


```{r}
situacao2
```


```{r}
situacao3
```


```{r}
situacao4
```


```{r}
situacao5
```


```{r}
situacao6
```


```{r}
situacao7
```


```{r}
amostra1<-sample(situacao1,TamanhoAmos[1])
```


```{r}
amostra2<-sample(situacao2,TamanhoAmos[2])
```


```{r}
amostra3<-sample(situacao3,TamanhoAmos[3])
```


```{r}
amostra4<-sample(situacao4,TamanhoAmos[4])
```


```{r}
amostra5<-sample(situacao5,TamanhoAmos[5])
```


```{r}
amostra6<-sample(situacao6,TamanhoAmos[6])
```


```{r}
amostra7<-sample(situacao7,TamanhoAmos[7])
```


```{r}
amostra7
```

```{r}
amostraest<-c(amostra1,amostra2,amostra3,amostra4,amostra5,amostra6,amostra7)
```


```{r}
amostraest
```


```{r}
Dataset <- readXL("C:/Users/diohe/Downloads/Dados_Renda_Trabalho01 (1).xlsx", rownames=FALSE, header=TRUE, na="",
sheet="Dados_Trabalho_01", stringsAsFactors=TRUE)
```


```{r}
dados <- Dataset$renda
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
situacao1<-c()
```


```{r}
situacao2<-c()
```


```{r}
situacao3<-c()
```


```{r}
situacao4<-c()
```


```{r}
situacao5<-c()
```


```{r}
situacao6<-c()
```


```{r}
situacao7<-c()
```


```{r}
c1<-1
```


```{r}
c2<-1
```


```{r}
c3<-1
```


```{r}
c4<-1
```


```{r}
c5<-1
```


```{r}
c6<-1
```


```{r}
c7<-1
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao2[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao3[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao4[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao5[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao6[c6]<-dados[i]
c6<-c6+1
} else if (situacao_laboral[i]=="7") {
situacao7[c7]<-dados[i]
c7<-c7+1
}
}
```


```{r}
situacao1
```


```{r}
situacao2
```


```{r}
situacao3
```


```{r}
situacao4
```


```{r}
situacao5
```


```{r}
situacao6
```


```{r}
situacao7
```


```{r}
amostra1<-sample(situacao1,TamanhoAmos[1])
```


```{r}
amostra2<-sample(situacao2,TamanhoAmos[2])
```


```{r}
amostra3<-sample(situacao3,TamanhoAmos[3])
```


```{r}
amostra4<-sample(situacao4,TamanhoAmos[4])
```


```{r}
amostra5<-sample(situacao5,TamanhoAmos[5])
```


```{r}
amostra6<-sample(situacao6,TamanhoAmos[6])
```


```{r}
amostra7<-sample(situacao7,TamanhoAmos[7])
```


```{r}
amostraest<-c(amostra1,amostra2,amostra3,amostra4,amostra5,amostra6,amostra7)
```


```{r}
amostraest
```


```{r}
amostra7
```


```{r}
summary(situacao_laboral)
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
N
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
amostraest
```


```{r}
mediaest<-mean(amostraest)
```


```{r}
mediaest
```


```{r}
mediaest<-mean(amostraest)
```


```{r}
mediaest
```


```{r}
mediapop<-mean(dados)
```


```{r}
erroest<-abs(mediaest-mediapop)
```


```{r}
erroest
```


```{r}
mediaest<-mean(amostraest)
```


```{r}
erroest
```


```{r}
erroest
```


```{r}
erroest
```


```{r}
Dataset <- readXL("C:/Users/diohe/Downloads/Dados_Renda_Trabalho01 (1).xlsx", rownames=FALSE, header=TRUE, na="",
sheet="Dados_Trabalho_01", stringsAsFactors=TRUE)
```


```{r}
dados <- Dataset$renda
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
situacao1<-c()
```


```{r}
situacao2<-c()
```


```{r}
situacao3<-c()
```


```{r}
situacao4<-c()
```


```{r}
situacao5<-c()
```


```{r}
situacao6<-c()
```


```{r}
situacao7<-c()
```


```{r}
c1<-1
```


```{r}
c2<-1
```


```{r}
c3<-1
```


```{r}
c4<-1
```


```{r}
c5<-1
```


```{r}
c6<-1
```


```{r}
c7<-1
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao2[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao3[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao4[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao5[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao6[c6]<-dados[i]
c6<-c6+1
} else if (situacao_laboral[i]=="7") {
situacao7[c7]<-dados[i]
c7<-c7+1
}
}
```


```{r}
situacao1
```


```{r}
situacao2
```


```{r}
situacao3
```


```{r}
situacao4
```


```{r}
situacao5
```


```{r}
situacao6
```


```{r}
situacao7
```


```{r}
amostra1<-sample(situacao1,TamanhoAmos[1])
```


```{r}
amostra2<-sample(situacao2,TamanhoAmos[2])
```


```{r}
amostra3<-sample(situacao3,TamanhoAmos[3])
```


```{r}
amostra4<-sample(situacao4,TamanhoAmos[4])
```


```{r}
amostra5<-sample(situacao5,TamanhoAmos[5])
```


```{r}
amostra6<-sample(situacao6,TamanhoAmos[6])
```


```{r}
amostra7<-sample(situacao7,TamanhoAmos[7])
```


```{r}
amostraest<-c(amostra1,amostra2,amostra3,amostra4,amostra5,amostra6,amostra7)
```


```{r}
amostraest
```


```{r}
mediaest<-mean(amostraest)
```


```{r}
mediaest
```


```{r}
mediapop<-mean(dados)
```


```{r}
erroest<-abs(mediaest-mediapop)
```


```{r}
erroest
```


```{r}
Dataset <- readXL("C:/Users/diohe/Downloads/Dados_Renda_Trabalho01 (1).xlsx", rownames=FALSE, header=TRUE, na="",
sheet="Dados_Trabalho_01", stringsAsFactors=TRUE)
```


```{r}
dados <- Dataset$renda
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
situacao1<-c()
```


```{r}
situacao2<-c()
```


```{r}
situacao3<-c()
```


```{r}
situacao4<-c()
```


```{r}
situacao5<-c()
```


```{r}
situacao6<-c()
```


```{r}
situacao7<-c()
```


```{r}
c1<-1
```


```{r}
c2<-1
```


```{r}
c3<-1
```


```{r}
c4<-1
```


```{r}
c5<-1
```


```{r}
c6<-1
```


```{r}
c7<-1
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao2[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao3[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao4[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao5[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao6[c6]<-dados[i]
c6<-c6+1
} else if (situacao_laboral[i]=="7") {
situacao7[c7]<-dados[i]
c7<-c7+1
}
}
```

```{r}
Dataset <- readXL("C:/Users/diohe/Downloads/Dados_Renda_Trabalho01 (1).xlsx", rownames=FALSE, header=TRUE, na="",
sheet="Dados_Trabalho_01", stringsAsFactors=TRUE)
```


```{r}
dados <- Dataset$renda
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
n<-150
```


```{r}
n
```


```{r}
situacao_laboral<-Dataset$Situacao_Laboral
```


```{r}
summary(situacao_laboral)
```


```{r}
N
```


```{r}
N1<-53663
```


```{r}
N2<-11704
```


```{r}
N3<-3733
```


```{r}
N4<-2055
```


```{r}
N5<-1994
```


```{r}
N6<-331
```


```{r}
N7<-179
```


```{r}
TamanhoPop<-c(N1,N2,N3,N4,N5,N6,N7)
```


```{r}
TamanhoPop
```


```{r}
TamanhoAmos<-round((TamanhoPop/N)*n,0)
```


```{r}
TamanhoAmos
```


```{r}
situacao1<-c()
```


```{r}
situacao2<-c()
```


```{r}
situacao3<-c()
```


```{r}
situacao4<-c()
```


```{r}
situacao5<-c()
```


```{r}
situacao6<-c()
```


```{r}
situacao7<-c()
```


```{r}
c1<-1
```


```{r}
c2<-1
```


```{r}
c3<-1
```


```{r}
c4<-1
```


```{r}
c5<-1
```


```{r}
c6<-1
```


```{r}
c7<-1
```


```{r}
for(i in 1:N) {
if(situacao_laboral[i]=="1") {
situacao1[c1]<-dados[i]
c1<-c1+1
} else if (situacao_laboral[i]=="2") {
situacao2[c2]<-dados[i]
c2<-c2+1
} else if(situacao_laboral[i]=="3") {
situacao3[c3]<-dados[i]
c3<-c3+1
} else if(situacao_laboral[i]=="4") {
situacao4[c4]<-dados[i]
c4<-c4+1
} else if(situacao_laboral[i]=="5") {
situacao5[c5]<-dados[i]
c5<-c5+1
} else if(situacao_laboral[i]=="6") {
situacao6[c6]<-dados[i]
c6<-c6+1
} else if (situacao_laboral[i]=="7") {
situacao7[c7]<-dados[i]
c7<-c7+1
}
}
```


```{r}
situacao1
```


```{r}
situacao2
```


```{r}
situacao3
```


```{r}
situacao4
```


```{r}
situacao5
```


```{r}
situacao6
```


```{r}
situacao7
```


```{r}
amostra1<-sample(situacao1,TamanhoAmos[1])
```


```{r}
amostra2<-sample(situacao2,TamanhoAmos[2])
```


```{r}
amostra3<-sample(situacao3,TamanhoAmos[3])
```


```{r}
amostra4<-sample(situacao4,TamanhoAmos[4])
```


```{r}
amostra5<-sample(situacao5,TamanhoAmos[5])
```


```{r}
amostra6<-sample(situacao6,TamanhoAmos[6])
```


```{r}
amostra7<-sample(situacao7,TamanhoAmos[7])
```


```{r}
amostraest<-c(amostra1,amostra2,amostra3,amostra4,amostra5,amostra6,amostra7)
```


```{r}
amostraest
```


```{r}
mediaest<-mean(amostraest)
```


```{r}
mediaest
```


```{r}
mediapop<-mean(dados)
```


```{r}
erroest<-abs(mediaest-mediapop)
```


```{r}
erroest
```


