<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### diohe

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```

```{r}
Dataset <- 
  readXL("C:/Users/diohe/OneDrive/Área de Trabalho/Portfolio/Estatistica/Tabelas/Dados_Aula_Pratica_Amostragem.xlsx",
   rownames=FALSE, header=TRUE, na="", sheet="Plan1", stringsAsFactors=TRUE)
```


### Summarize Data Set: Dataset
```{r}
summary(Dataset)
```


```{r}
dados <- Dataset$Idade
```


```{r}
dados
```


```{r}
Dataset <-
readXL("C:/Users/diohe/OneDrive/Área de Trabalho/Portfolio/Estatistica/Tabelas/Dados_Aula_Pratica_Amostragem.xlsx",
rownames=FALSE, header=TRUE, na="", sheet="Plan1", stringsAsFactors=TRUE)
```


```{r}
summary(Dataset)
```


```{r}
dados <- Dataset$Idade
```


```{r}
tabela<-function(dados,cd) {
A<-max(dados)-min(dados)
n<-length(dados)
if(n<=100) {
k<-ceiling(sqrt(n))
} else {
k<-ceiling(5*log10(n))
}
C<-round(A/(k-1),cd)
LI<-c(rep(0,(k+1)))
media<-c(NA)
LI[1]<-round(min(dados)-(C)/2,cd)
for(i in 2:(k+1)) {
LI[i]<-round(LI[i-1]+C,cd)
media[i-1]<-mean(c(LI[i],LI[i-1]))
}
limites<-LI
TDF<-hist(dados,breaks=limites,plot=FALSE,right=FALSE)
tabela<-matrix(c(rep(6*k)),k,6)
for(i in 1:k) {
tabela[i,1]<-round(LI[i],cd)
tabela[i,2]<-round(LI[i+1],cd)
tabela[i,3]<-round(media[i],cd)
tabela[i,4]<-(TDF$counts[i])
tabela[i,5]<-round(((TDF$counts[i])/n),5)
tabela[i,6]<-round((100*TDF$counts[i])/n,3)
}
colnames(tabela)<-c("LI","LS","X","Fa","Fr","Fp")
return(tabela)
}
```


```{r}
quebras<-function(dados,cd) {
A<-max(dados)-min(dados)
n<-length(dados)
if(n<=100) {
k<-ceiling(sqrt(n))
} else {
k<-ceiling(5*log10(n))
}
C<-round(A/(k-1),cd)
LI<-c(rep(0,(k+1)))
LI[1]<-round(min(dados)-(C)/2,cd)
for(i in 2:(k+1)) {
LI[i]<-round(LI[i-1]+C,cd)
}
return(LI)
}
```

```{r}
Dataset <-
readXL("C:/Users/diohe/OneDrive/Área de Trabalho/Portfolio/Estatistica/Tabelas/Dados_Aula_Pratica_Amostragem.xlsx",
rownames=FALSE, header=TRUE, na="", sheet="Plan1", stringsAsFactors=TRUE)
```


```{r}
summary(Dataset)
```


```{r}
dados <- Dataset$Idade
```


```{r}
tabela<-function(dados,cd) {
A<-max(dados)-min(dados)
n<-length(dados)
if(n<=100) {
k<-ceiling(sqrt(n))
} else {
k<-ceiling(5*log10(n))
}
C<-round(A/(k-1),cd)
LI<-c(rep(0,(k+1)))
media<-c(NA)
LI[1]<-round(min(dados)-(C)/2,cd)
for(i in 2:(k+1)) {
LI[i]<-round(LI[i-1]+C,cd)
media[i-1]<-mean(c(LI[i],LI[i-1]))
}
limites<-LI
TDF<-hist(dados,breaks=limites,plot=FALSE,right=FALSE)
tabela<-matrix(c(rep(6*k)),k,6)
for(i in 1:k) {
tabela[i,1]<-round(LI[i],cd)
tabela[i,2]<-round(LI[i+1],cd)
tabela[i,3]<-round(media[i],cd)
tabela[i,4]<-(TDF$counts[i])
tabela[i,5]<-round(((TDF$counts[i])/n),5)
tabela[i,6]<-round((100*TDF$counts[i])/n,3)
}
colnames(tabela)<-c("LI","LS","X","Fa","Fr","Fp")
return(tabela)
}
```


```{r}
tabela(dados,1)
```


```{r}
porcentagem<-tabela(dados,1)[6]
```


```{r}
porcentagem
```


```{r}
porcentagem<-tabela(dados,1)[,6]
```


```{r}
porcentagem
```


```{r}
sum(porcentagem[1:6])
```


```{r}
tabela(dados,1)
```


```{r}
print("hello world")
```

```{r}
quebras<-function(dados,cd) {
A<-max(dados)-min(dados)
n<-length(dados)
if(n<=100) {
k<-ceiling(sqrt(n))
} else {
k<-ceiling(5*log10(n))
}
C<-round(A/(k-1),cd)
LI<-c(rep(0,(k+1)))
LI[1]<-round(min(dados)-(C)/2,cd)
for(i in 2:(k+1)) {
LI[i]<-round(LI[i-1]+C,cd)
}
return(LI)
}
```


```{r}
limites<-quebras(dados,3)
```


```{r}
limites
```


```{r}
TDF<-hist(dados,breaks=limites,plot=FALSE,right=FALSE)
```


```{r}
TDF
```


```{r}
TDF<-hist(dados,breaks=limites,plot=FALSE,right=FALSE)
```


```{r}
TDF
```

```{r}
quebras<-function(dados,cd) {
A<-max(dados)-min(dados)
n<-length(dados)
if(n<=100) {
k<-ceiling(sqrt(n))
} else {
k<-ceiling(5*log10(n))
}
C<-round(A/(k-1),cd)
LI<-c(rep(0,(k+1)))
LI[1]<-round(min(dados)-(C)/2,cd)
for(i in 2:(k+1)) {
LI[i]<-round(LI[i-1]+C,cd)
}
return(LI)
}
```


```{r}
limites<-quebras(dados,3)
```


```{r}
limites
```


```{r}
TDF<-hist(dados,breaks=limites,plot=FALSE,right=FALSE)
```


```{r}
TDF
```

```{r}
quebras<-function(dados,cd) {
A<-max(dados)-min(dados)
n<-length(dados)
if(n<=100) {
k<-ceiling(sqrt(n))
} else {
k<-ceiling(5*log10(n))
}
C<-round(A/(k-1),cd)
LI<-c(rep(0,(k+1)))
LI[1]<-round(min(dados)-(C)/2,cd)
for(i in 2:(k+1)) {
LI[i]<-round(LI[i-1]+C,cd)
}
return(LI)
}
```


```{r}
limites<-quebras(dados,3)
```


```{r}
limites
```


```{r}
TDF<-hist(dados,breaks=limites,plot=FALSE,right=FALSE)
```


```{r}
TDF
```


```{r}
hist(
dados,label=FALSE,main="",
xlab=expression(paste("Idade (Anos)")),
ylab="Frequencia absoluta",
ylim=c(0,(max(TDF$counts)+1)),
breaks=limites,axes=FALSE,right=FALSE
)
```


```{r}
axis(1,at=limites,pos=c(0,0))
```


```{r}
axis(2,at=c(seq(0:(max(TDF$counts)+1))-1))
```


```{r}
Dataset <- within(Dataset, {
  Aprendeu <- as.factor(Aprendeu)
})
```


### Bar Plot: Aprendeu
```{r}
with(Dataset, Barplot(Aprendeu, xlab="Aprendeu", ylab="Frequency", label.bars=TRUE))
```


### Bar Plot: Aprendeu
```{r}
with(Dataset, Barplot(Aprendeu, xlab="Forma que o trabalhador de TI aprendeu a programar", ylab="Frequencia", 
  label.bars=TRUE))
```


### Bar Plot: Aprendeu
```{r}
with(Dataset, Barplot(Aprendeu, xlab="Forma que o trabalhador de TI aprendeu a programar", ylab="Frequencia", 
  scale="percent", label.bars=TRUE))
```

```{r}
library(colorspace, pos=16)
```



### Pie Chart: Atuacao
```{r}
with(Dataset, piechart(Atuacao, xlab="Atuacao do entusiasta de TI", ylab="", main="Atuacao", col=rainbow_hcl(3), 
  scale="percent"))
```

```{r}
library(abind, pos=17)
```


```{r}
library(e1071, pos=18)
```



### Resumos Numéricos: Dataset
```{r}
numSummary(Dataset[,"Idade", drop=FALSE], statistics=c("mean", "sd", "quantiles", "CV"), quantiles=c(0,.25,.5,.75,
  1))
```

```{r}
quebras<-function(dados,cd) {
A<-max(dados)-min(dados)
n<-length(dados)
if(n<=100) {
k<-ceiling(sqrt(n))
} else {
k<-ceiling(5*log10(n))
}
C<-round(A/(k-1),cd)
LI<-c(rep(0,(k+1)))
LI[1]<-round(min(dados)-(C)/2,cd)
for(i in 2:(k+1)) {
LI[i]<-round(LI[i-1]+C,cd)
}
return(LI)
}
```


```{r}
limites<-quebras(dados,3)
```


```{r}
limites
```


```{r}
TDF<-hist(dados,breaks=limites,plot=FALSE,right=FALSE)
```


```{r}
TDF
```


```{r}
hist(
dados,label=FALSE,main="",
xlab=expression(paste("Idade (Anos)")),
ylab="Frequencia absoluta",
ylim=c(0,(max(TDF$counts)+1)),
breaks=limites,axes=FALSE,right=FALSE
)
```


```{r}
axis(1,at=limites,pos=c(0,0))
```


```{r}
axis(2,at=c(seq(0:(max(TDF$counts)+1))-1))
```



### Boxplot: ~ Idade
```{r}
Boxplot( ~ Idade, data=Dataset, id=list(method="y"))
```

